name: "Android App Tests"

on:

  workflow_call:
    inputs:
      app_workspace:
        description: "App workspace path"
        required: true
        default: "./"
        type: string

jobs:

  android-instrumented-tests:
    name: "Instrumented Tests"
    timeout-minutes: 30
    runs-on: macos-13
    strategy:
      matrix:
        api-level: [29]
#        target: [google_apis]
#        arch: [arm64-v8a]
    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "Install JDK 17"
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
      - name: "Run Instrumented Tests"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          working-directory: ${{ inputs.app_workspace }}
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          avd-name: "avd-${{ matrix.api-level }}"
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew cAT
      - name: "Archive Instrumented Tests Results"
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: "instrumented-tests-results-${{ matrix.api-level }}"
          path: ./**/build/reports/androidTests/connected/**

  android-unit-tests:
    name: "Android Unit Tests"
    runs-on: ubuntu-latest
    steps:
        - name: "Checkout"
          uses: actions/checkout@v4
        - name: "Install JDK 17"
          uses: actions/setup-java@v4
          with:
            distribution: "zulu"
            java-version: "17"
            cache: "gradle"
        - name: "Run Unit Tests"
          working-directory: ${{ inputs.app_workspace }}
          run: ./gradlew test
        - name: "Android Unit Tests Report"
          uses: actions/upload-artifact@v3
          if: ${{ always() }}
          with:
            name: "unit-tests-results"
            path: ./**/build/reports/**

  android-lint:
    name: "Android Lint Checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install JDK 17"
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
      - name: "Run Lint Checks"
        working-directory: ${{ inputs.app_workspace }}
        run: ./gradlew lint
      - name: "Archive Lint Test Results"
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: "lint-results"
          path: ./**/build/reports/**

  android-kotlin-lint:
    name: "Android Kotlin Lint Checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install JDK 17"
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
      - name: "Run Kotlin Lint Checks"
        working-directory: ${{ inputs.app_workspace }}
        run: ./gradlew ktlintCheck
      - name: "Archive Lint Test Results"
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: "kotlin-lint-results"
          path: ./**/build/reports/**
